# Generated by Django 6.0.2 on 2026-02-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userme',
            name='swaps_used',
        ),
        migrations.AddField(
            model_name='token',
            name='swaps_used',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='rnr.queue')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='rnr.token')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='rnr.token')),
            ],
        ),
    ]
