# Generated by Django 5.2.6 on 2026-02-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0002_remove_userme_swaps_used_token_swaps_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLING', 'Calling'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20),
        ),
    ]
